name: bzy_network_framework
description: BZY 统一网络请求框架 - 高性能、易扩展的 Flutter 网络解决方案
version: 1.0.2
homepage: https://github.com/SQDuanZC/bzy_network_framework
repository: https://github.com/SQDuanZC/bzy_network_framework
issue_tracker: https://github.com/SQDuanZC/bzy_network_framework/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.2
  logging: ^1.2.0
  device_info_plus: ^9.1.0
  package_info_plus: ^4.2.0
  connectivity_plus: ^5.0.1
  shared_preferences: ^2.2.2
  json_annotation: ^4.8.1
  crypto: ^3.0.3
  archive: ^3.4.10
  synchronized: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  flutter_lints: ^3.0.0
  mockito: ^5.4.0
  test: ^1.24.0

# 如果是纯 Dart 包，移除 flutter.plugin 配置
# 如果需要原生代码，保留 flutter.plugin 配置
flutter:
  # plugin:
  #   platforms:
  #     android:
  #       package: com.bzy.network_framework
  #       pluginClass: BzyNetworkFrameworkPlugin
  #     ios:
  #       pluginClass: BzyNetworkFrameworkPlugin

topics:
  - network
  - http
  - dio
  - flutter
  - framework
  - bzy

# screenshots:
#   - description: 'BZY 网络框架架构图'
#     path: screenshots/architecture.png
#   - description: '性能监控面板'
#     path: screenshots/monitoring.png

funding:
  - https://github.com/sponsors/SQDuanZC