name: bzy_network_framework
description: BZY 统一网络请求框架 - 高性能、易扩展的 Flutter 网络解决方案
version: 1.0.0
homepage: https://github.com/your-org/bzy_network_framework
repository: https://github.com/your-org/bzy_network_framework
issue_tracker: https://github.com/your-org/bzy_network_framework/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # 网络请求核心库
  dio: ^5.3.2
  
  # 日志系统
  logging: ^1.2.0
  
  # 设备信息获取
  device_info_plus: ^9.1.0
  
  # 应用包信息获取
  package_info_plus: ^4.2.0
  
  # 网络连接状态检测
  connectivity_plus: ^5.0.1
  
  # 本地存储（用于缓存）
  shared_preferences: ^2.2.2
  
  # JSON 序列化
  json_annotation: ^4.8.1
  
  # 加密库
  crypto: ^3.0.3
  
  # 压缩库
  archive: ^3.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # JSON 序列化代码生成
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  
  # 代码分析
  flutter_lints: ^3.0.0
  
  # 测试工具
  mockito: ^5.4.0
  test: ^1.24.0

# Flutter 包配置
flutter:
  # 这是一个插件包
  plugin:
    platforms:
      android:
        package: com.bzy.network_framework
        pluginClass: BzyNetworkFrameworkPlugin
      ios:
        pluginClass: BzyNetworkFrameworkPlugin

# 发布配置
topics:
  - network
  - http
  - dio
  - flutter
  - framework
  - bzy

# screenshots:
#   - description: 'BZY 网络框架架构图'
#     path: screenshots/architecture.png
#   - description: '性能监控面板'
#     path: screenshots/monitoring.png

funding:
  - https://github.com/sponsors/your-org